name: Build LaTeX and Upload PDF
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload zip containing PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
      - name: Upload PDF to Releases Page
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf